version: '3.8'
services:
  #PHP Service 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: linux-console.net/php
    container_name: app-ku-lib-frontend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-ku-lib-frontend
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    #networks:
    #  - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: app-ku-lib-frontend-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8081"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    #networks:
    #  - app-network

  #Docker Networks
  #networks:
  #  app-network:
  #    driver: bridge